### ISSUE TITLE
Windows 10 21H2 LTSC is reported as obsolete OS

### ISSUE THREAD

**Issue by mathse** [netwrix/pingcastle#243] opened 2024-07-30 13:59 UTC
... all other LTSC/LTSB OSes seam fine

Pingcastle Version 3.2.0.1

**Comment by JoeDibley** [comment] 2024-09-12 15:49
Hi there,
The LTSC / LTSB checks are literally checking for LTSC in the operating system name, the Active Directory OperatingSystem attribute. Are you sure the operating systems that were shown are actually the LTSC versions?

You can see this in the HealthCheckData.cs below
https://github.com/netwrix/pingcastle/blob/502535913aa774c9be6cd24fdcabc894436f005b/Data/HealthcheckData.cs#L813-L820

The Obsolete check then uses the IsLTSC to determine the timeframe of the support.
https://github.com/netwrix/pingcastle/blob/502535913aa774c9be6cd24fdcabc894436f005b/Healthcheck/Rules/HeatlcheckRuleStaledObsoleteW10.cs#L74-L91

**Comment by mathse** [comment] 2024-09-13 09:27
I had a look at our AD data using Excel (yes yes I know)
Excel -> 223 eol os's
Pingcastle -> 993 eol os's

Still pretty sure that there is something wrong

**Comment by JoeDibley** [comment] 2024-09-13 09:51
Great spot on the missing LTSC. Missed that yesterday. So seems like the IsLTSC check may be okay and just an issue on the reporting side due to that. Will let you know when we have a release with this resolved.

**Comment by JoeDibley** [comment] 2024-09-16 09:41
This is resolved in the 3.3.0 release. Thanks again for reporting.

**Comment by mathse** [comment] 2024-09-18 11:45
> This is resolved in the 3.3.0 release. Thanks again for reporting.

Nope it's not

**Comment by JoeDibley** [comment] 2024-09-18 12:20
I may have taken an assumption here. The code was already updated when I checked out the internal version but didn't specifically test this. I have an idea of where this bug now after some quick debugging. Will keep you posted.

**Comment by JoeDibley** [comment] 2024-09-19 09:39
Confirmed the bug was in the way the OS Versions were built due to a key not including the LTSC differences. Updated and tested and now both OS's seem to report correctly. We should have a new release out over the next day or so. Will drop another reply when out.

**Comment by JoeDibley** [comment] 2024-09-26 13:07
This should now be resolved in the 3.3.0.1 version. Please reopen again if you believe there to be an issue. 

Thanks again for reporting!

**Closed by JoeDibley** 2024-09-26 13:07 UTC
Labels: bug
