### ISSUE TITLE
Item has already been added

### ISSUE THREAD

**Issue by idefixgallier** [netwrix/pingcastle#261] opened 2024-09-24 06:03 UTC
Hey!
The healthscanner does not work any more:

_Free Edition of PingCastle 3.3.0 - Not for commercial use
Starting the task: Perform analysis for XXX.local
[07:40:30] Getting domain information (XXX.local)
Performance warning: using LDAP instead of ADWS
[07:41:13] Gathering general data
[07:41:14] This domain contains approximatively 30526 objects
[07:41:14] Gathering user data
[07:41:21] An exception occured when doing the task: Perform analysis for XXX.local
[07:41:21] An exception occured when doing the task: Perform analysis for XXX.local
Note: you can run the program with the switch --log to get more detail
Exception: Item has already been added. **Key in dictionary: 'objectsid'  Key being added: 'objectsid'**
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.DictionaryBase.System.Collections.IDictionary.Add(Object key, Object value)
   at System.DirectoryServices.Extensions.CompleteHintInformationIfNeeded(Object searchResultObject, IEnumerable`1 entries)
   at System.DirectoryServices.SearchResultCollection.get_InnerList()
   at System.DirectoryServices.SearchResultCollection.GetEnumerator()
   at PingCastle.ADWS.LDAPConnection.EnumerateInternalWithLDAP(String distinguishedName, String filter, String[] properties, String scope, WorkOnReturnedObjectByADWS callback)
   at PingCastle.ADWS.ADWebService.Enumerate(Action preambleWithReentry, String distinguishedName, String filter, String[] properties, WorkOnReturnedObjectByADWS callback, String scope)
   at PingCastle.Healthcheck.HealthcheckAnalyzer.GenerateUserData(ADDomainInfo domainInfo, ADWebService adws)
   at PingCastle.Healthcheck.HealthcheckAnalyzer.PerformAnalyze(PingCastleAnalyzerParameters parameters)
   at PingCastle.Tasks.<>c__DisplayClass30_0.<PerformTheAnalysis>b__0()
   at PingCastle.Tasks.StartTask(String taskname, TaskDelegate taskdelegate)_

We checked if we do have duplicate SIDs with ntdsutil but we haven't found any....
How can we help to solve this?

kr
Martin

**Comment by JoeDibley** [comment] 2024-09-26 19:06
Hi there,
Thanks for the issue. This will likely be an issue with the specific domain controller scanned. You will need to run the NTDSUtil duplicate sids check on all your domain controllers not just a single one to identify the issue. 

Alternatively you can use `pingcastle.exe --healthcheck --server DCName` or specify a domain controller when you specify the domain on the interactive scan.

I will be adding something to the backlog to handle the objectsid better.

**Comment by JoeDibley** [comment] 2024-10-09 16:53
Hi there,
Just checking in, did you managed to check this out any further?

**Comment by idefixgallier** [comment] 2024-10-09 17:21
It's some kind of ASR rule or Defender magic, but we didn't have time to investigate it further.
It's work in progress and I'll report back

Sent from Nine
________________________________

**Comment by idefixgallier** [comment] 2024-10-24 10:01
Hey!

 

We haven’t been able to identify a cause why ping castle delivers that error on certain  clients.
We still think that MS defender is the culprit but we cannot pinpoint an exact cause.

 

At lease we know on what clients its working and can use it ….

 

Thank you Joe

**Comment by JoeDibley** [comment] 2024-10-24 10:05
No problem at all. I'll close this for now but please do reopen or log a new issue if you discover the cause.

**Closed by JoeDibley** 2024-10-24 10:05 UTC
